package transport

import (
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"sort"
	"strings"
)

type Environment struct {
	SchemaVersion int               `json:"schema_version"`
	Mode          string            `json:"mode"`
	Runtime       string            `json:"runtime"`
	Variables     map[string]string `json:"variables"`
}

func LoadPairReport(path string) (PairReport, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return PairReport{}, err
	}
	var p PairReport
	if err := json.Unmarshal(b, &p); err != nil {
		return PairReport{}, err
	}
	if p.SchemaVersion != SchemaVersion {
		return PairReport{}, fmt.Errorf("unsupported pair transport schema %d", p.SchemaVersion)
	}
	return p, nil
}

func GenerateEnvironment(local Report, pair *PairReport, mode, runtimeName string) (Environment, error) {
	if mode == "" {
		mode = "auto"
	}
	if runtimeName == "" {
		runtimeName = "generic"
	}
	if mode != "auto" && mode != "portable" && mode != "nhi" {
		return Environment{}, errors.New("mode must be auto, portable, or nhi")
	}
	if runtimeName != "generic" && runtimeName != "vllm" && runtimeName != "pytorch" {
		return Environment{}, errors.New("runtime must be generic, vllm, or pytorch")
	}
	if !local.Portable.Ready {
		return Environment{}, errors.New("portable local transport is not ready")
	}
	if pair != nil && !pair.PortableReady {
		return Environment{}, errors.New("portable pair transport is not ready")
	}
	if pair != nil && pair.Fallback.CleanupRequired {
		return Environment{}, errors.New("pair has partial NHI state; clean both endpoints before generating any fallback environment")
	}
	selected := mode
	if selected == "auto" {
		selected = "portable"
		if pair != nil && pair.NHIReady && pair.LeaseAvailable && endpointExact(local) {
			selected = "nhi"
		}
	}
	if selected == "nhi" {
		if pair == nil || !pair.NHIReady || !pair.LeaseAvailable {
			return Environment{}, errors.New("NHI environment requires a reconciled pair report with nhi_ready=true and lease_available=true")
		}
		if !endpointExact(local) {
			return Environment{}, errors.New("local NHI endpoint does not match the reconciled production profile")
		}
	}
	// Prefer the address recorded in the (freshly inspected or reviewed) report;
	// fall back to a live interface lookup for older callers.
	localAddr := local.LocalAddress
	if localAddr == "" {
		localAddr = InterfaceIPv4(local.Interface)
	}
	vars := map[string]string{
		"CIRU_STRIXLINK_SCHEMA":        fmt.Sprint(SchemaVersion),
		"CIRU_STRIXLINK_MODE":          selected,
		"CIRU_STRIXLINK_INTERFACE":     local.Interface,
		"CIRU_STRIXLINK_LOCAL_ADDRESS": localAddr,
		"CIRU_STRIXLINK_PEER":          local.Peer,
		"CIRU_STRIXLINK_NETWORK_HOPID": fmt.Sprint(ExpectedNetHopID),
		"NCCL_SOCKET_IFNAME":           "=" + local.Interface,
		"NCCL_SOCKET_FAMILY":           "AF_INET",
		"GLOO_SOCKET_IFNAME":           local.Interface,
	}
	if selected == "nhi" {
		e := local.Endpoints[0]
		vars["CIRU_STRIXLINK_NHI_DEVICE"] = e.Device
		vars["CIRU_STRIXLINK_NHI_RING_SIZE"] = fmt.Sprint(e.RingSize)
		vars["CIRU_STRIXLINK_NHI_THROTTLING_NS"] = fmt.Sprint(e.ThrottlingNS)
		vars["CIRU_STRIXLINK_NHI_IN_HOPID"] = fmt.Sprint(e.InHopID)
		vars["CIRU_STRIXLINK_NHI_OUT_HOPID"] = fmt.Sprint(e.OutHopID)
		vars["CIRU_STRIXLINK_CAP_SYS_RAWIO_REQUIRED"] = "1"
		if runtimeName == "vllm" {
			vars["VLLM_NHI_DEVICE"] = e.Device
		}
	}
	return Environment{SchemaVersion: SchemaVersion, Mode: selected, Runtime: runtimeName, Variables: vars}, nil
}

func (e Environment) DotEnv() string {
	keys := make([]string, 0, len(e.Variables))
	for key := range e.Variables {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by CiruStrixLink; mode=%s runtime=%s\n", e.Mode, e.Runtime)
	for _, key := range keys {
		fmt.Fprintf(&b, "%s=%s\n", key, e.Variables[key])
	}
	return b.String()
}

func ParseDotEnv(path string) (map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	out := make(map[string]string)
	s := bufio.NewScanner(f)
	for s.Scan() {
		line := strings.TrimSpace(s.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok || key == "" {
			return nil, fmt.Errorf("invalid environment line %q", line)
		}
		out[key] = value
	}
	return out, s.Err()
}
